-- Migration to apply generated lore to existing anime shop_items

WITH new_lore (name, description, source_anime) AS (
  VALUES
    ('Adolla Burst', 'Fogo puro oriundo de outra dimensão capaz de incinerar qualquer impureza com o calor do próprio sol.', 'Fire Force'),
    ('Anti-Magic Slash', 'Um golpe pesado coberto de anti-magia que anula defesas e encantos inimigos instantaneamente.', 'Black Clover'),
    ('Arthur’s Excalibur', 'Uma lâmina de plasma cujo poder cresce conforme a convicção do usuário em si mesmo como um cavaleiro real.', 'Fire Force'),
    ('Automail Blade', 'Lâmina cibernética retrátil ligada aos nervos do corpo, afiada o suficiente para cortar metal.', 'Fullmetal Alchemist'),
    ('Avalon', 'Bainha sagrada que cura as feridas de seu portador e invoca uma utopia inatingível, isolando todas as ameaças.', 'Fate'),
    ('Baruka’s Dagger', 'Adaga gélida usada pelo Rei dos Elfos de Gelo. Seus cortes paralisam os nervos com calafrios.', 'Solo Leveling'),
    ('Behelit', 'Um artefato perturbador na forma de um ovo com feições humanas, ligado aos temíveis God Hand da profundeza astral.', 'Berserk'),
    ('Benimaru’s Crimson Moon', 'Um pilar cortante de chamas carmesim. O ápice do estilo Iaijutsu da sétima brigada de Tóquio.', 'Fire Force'),
    ('Berserker Armor', 'Armadura maldita que adormece a dor e destrava a fúria do corpo humano além dos limites, quebrando os próprios ossos no processo.', 'Berserk'),
    ('Berserker Rag', 'Trapo marcado por inúmeras batalhas sangrentas, imbuído de puro instinto de sobrevivência e pura fúria.', 'Berserk'),
    ('Black Divider', 'Invoca uma gigantesca espada envolta em anti-magia densa, capaz de partir tanto feitiços quanto montanhas.', 'Black Clover'),
    ('Black Flash', 'Uma distorção espacial que ocorre milissegundos após o impacto físico aplicando energia amaldiçoada intensa. Aumenta absurdamente o golpe.', 'Jujutsu Kaisen'),
    ('Bloodlust', 'Uma aura aterrorizante capaz de fazer até o mais valente dos guerreiros hesitar de puro e gélido desespero.', 'Solo Leveling'),
    ('Cannon Arm', 'Prótese de aço maciço que oculta um canhão de pólvora negra para ataques explosivos a curta distância.', 'Berserk'),
    ('Chain Jail', 'Correntes impiedosas temperadas em Nen capazes de prender e forçar seres a um estado indefeso.', 'Hunter x Hunter'),
    ('Chastiefol', 'Lança Espiritual da Árvore Sagrada. Suas diversas formas mortais e regenerativas punem a desonestidade.', 'Seven Deadly Sins'),
    ('Cruel Sun', 'Moldando o calor de mil sóis ao toque brutal do sol do meio-dia, o poder diminui as trevas do inimigo até a cinza.', 'Seven Deadly Sins'),
    ('Cursed Speech', 'Sua afluência infunde palavras de comando absolutas em quem ouve, forçando ações que distorcem a realidade ao redor.', 'Jujutsu Kaisen'),
    ('Dark Magician', 'O mago sombrio por excelência, conjurando ataques impiedosos e magias astrais arcanas na ponta do cajado.', 'Yu-Gi-Oh!'),
    ('Dark Shadow', 'Uma entidade das sombras habitando o espírito do usuário. Torna-se letal nas trevas e feroz quanto mais avança a escuridão.', 'My Hero Academia'),
    ('Death Scythe', 'Uma foice ressonante desenvolvida especificamente para extinguir, devorar e ceifar as mais antigas almas corruptas.', 'Soul Eater'),
    ('Demon Sword Ragnarok', 'Arma que pode se grudar no seu sangue com espinhos demoníacos, gritando enlouquecedoramente para ensurdecer os oponentes.', 'Soul Eater'),
    ('Dimension Slash', 'Corte de anti-magia escuro capaz de fraturar e rasgar não só defesas divinas, como o próprio espaço.', 'Black Clover'),
    ('Direct Shot', 'Chute sem preparação anterior, puro pragmatismo e técnica, sem permitir chances para reação e reflexão do oponente.', 'Blue Lock'),
    ('Disaster', 'Poder mágico enraigado sobre o estado natural dos seres orgânicos - pode inflar venenos, tumores, hemorragias ou acelerar apodrecimento na carne e planta.', 'Seven Deadly Sins'),
    ('Domain Expansion', 'Manifestação inata que expande o terreno da alma, transformando a mente, regra e poder numa masmorra intransitável com acertos garantidos.', 'Jujutsu Kaisen'),
    ('Dragon Balls', 'Esferas míticas que dizem abrigar a vontade divina do sopro de dragões estrelares. O limite de seu milagre não tem fim.', 'Dragon Ball'),
    ('Dragon Cleave', 'Investida brutal desenhada do movimento natural dos dragões, talho profundo feito para fraturar espessas couraças.', 'Hunter x Hunter'),
    ('Dragon Force', 'Ativa instintos antigos fundindo as próprias células com fragmentos dracônicos que impulsionam agressão escamosa incomparável.', 'Fairy Tail'),
    ('Dragon Lacrima', 'Um cristal contendo pura força mística do dragão em estado bruto. Ingerir ou assimilar suas lascas molda habilidades inumanas.', 'Fairy Tail'),
    ('Dragon of the Darkness Flame', 'Chamas obscuras do Mundo das Trevas purificadas da destruição desenrolando uma calamidade de terror em formato de dragão negro.', 'Yu Yu Hakusho'),
    ('Dragon Slayer', 'Uma massa tão colossal, desajeitada e pesada de ferro cru imbuída na fúria contra apóstolos imortais. Não devia ser chamada de espada.', 'Berserk'),
    ('enma', 'Lâmina devoradora de Haki de alto risco cortando violentamente tudo pela frente.', 'One Piece'),
    ('Enuma Elish', 'Espada primordial criadora do firmamento. A lufada giratória deste pilar vermelho desfaz a consistência das dimensões até restarem poeira.', 'Fate'),
    ('Equivalent Exchange', 'Técnica fundamental: Para obter algo valioso algo de mesmo valor místico se paga. Não permite magia baseada do puro vazio.', 'Fullmetal Alchemist'),
    ('Erasure', 'Visão sufocante apagadora temporária de genes e quirks orgânicos enraizados por poderes. Exige que as pálpebras não voltem.', 'My Hero Academia'),
    ('Erza’s Armors', 'Coleção de ligas divinas evocadas nas horas precisas - desde voos a defesas de raios ou manuseio simultâneo de inumeras pás ardentes.', 'Fairy Tail'),
    ('Excalibur', 'A espada da vitória e promessa que queima os obstáculos, exalando auroras reluzentes por justiça imaculável.', 'Fate'),
    ('Explosion Rush', 'Propulsão de suor na forma de nitropenta destrutiva, criando explosões brutais e incessantes sem dar ritmo ao alvo.', 'My Hero Academia'),
    ('Fairy Tail Mark', 'A marca dourada imbuída de lealdade e força do laço dos companheiros imbatíveis frente ao abismo.', 'Fairy Tail'),
    ('Final Flash', 'Um disparo duplo de ki carregado movido sob mais agudo escárnio pelo desespero absoluto dos deuses arrogantes.', 'Dragon Ball'),
    ('Fire Dragon Roar', 'A foz rugidora explodindo o oxigênio num redemoinho calcinante gerado nas entranhas de guerreiros Dracônicos natos.', 'Fairy Tail'),
    ('Flame Alchemy', 'Friccionar os dedos para criar ignição numa nuvem instável de gases inflamáveis focados diretamente sobre os iníquos e homúnculos.', 'Fullmetal Alchemist'),
    ('foice tripla', 'Arma com lâminas curívas interligadas, impossibilita defesas fáceis arrancando ganchos profundos de retaliação maldosa das sombras.', 'Anime'),
    ('Full Counter', 'Revida qualquer energia ou dano etéreo desproporcionalmente refletido na cara do remetente impiedosamente com potência multiplicada.', 'Seven Deadly Sins'),
    ('Geass Eye', 'Olho que corrompe corações ditando comando mental supremo ao observar a íris de suas cobaias inermes, para os devotos caírem pelo tabuleiro.', 'Code Geass'),
    ('Gideon', 'Desproporcional para humanos. Um martelo bélico retorcido incutindo controle esmortalhante sob magmas e falhas tectônicas da crosta terrestre.', 'Seven Deadly Sins'),
    ('Godspeed', 'Canaliza e absorve puras faíscas vitrificantes permitindo se adiantar nos reflexos e mover até mais ligeiro que neurônios.', 'Hunter x Hunter'),
    ('gomu gomu no mi', 'Fruta rústica originária das veias ancestrais, trazendo dons expansíveis incansáveis da liberdade do ritmo bongo.', 'One Piece'),
    ('Gon’s Fishing Rod', 'Ferramenta singela e rudimentar para manusear as correntes e iscar pontos flácidos inatingíveis num mar esquisito e assombrante de perigos.', 'Hunter x Hunter'),
    ('gura gura', 'Impacto telúrico que reverbera fissuras nos ossos, atmosfera ou montanhas. O caos em formato geológico e sísmico das batidas de deuses marinhos.', 'One Piece'),
    ('Half-Cold Half-Hot', 'Equilíbrio de dois pólos termodinâmicos extremos simultâneos em calafrio criogênico imenso em um passo de incêndios devastantes em chamas rubras no repúdio cego.', 'My Hero Academia'),
    ('Hamon Overdrive', 'Impactos reluzentes solares oriundos pelo fulgor profundo gerado pelos pulsos de uma técnica compassada sobre uma respiração viva controlando e matando o lado das trevas redivivo no vampirismo ou não-vivo dos pilares.', 'JoJo'),
    ('Hinokami Kagura', 'Uma antiga e harmoniosa dança milenar em nome dos deuses vulcânicos e faíscas. A combustão solar converte agonia num ciclo fulgurante em fúria eterna para extermínio dos pesadelos demoníacos.', 'One Piece'),
    ('Hisoka’s Cards', 'Cartas que parecem normais até perfurarem artérias cortadas a laser na fluidez pegajosa ou goma chicletosa da sua malícia cômica.', 'Hunter x Hunter'),
    ('Hollow Purple', 'Paradoxo gerado na singularidade esmagando pólos azuis de atração com repulsões escarlates extirpando da realidade os alvos da aniquilação maciça roxa no vazio implacável do imensurável absurdo de sua superior face etérea da distorção do vácuo infinito da esfera imaginária vazia irrestrita irônica de Gojo satoru.', 'Jujutsu Kaisen'),
    ('Hyorinmaru', 'Fria exsudação de aura congelando tudo condensadamente pelo ressoar imenso no gelado dragão branco celeste a zero graus.', 'Bleach'),
    ('Ice Make', 'Alquimia em ritmo rápido gerando de muralhas águias atiradores ou escudos instantâneos a bel prazer sob um congelamento em contorno artístico na precisão infinita de um exímio ferreiro do gelo no frio.', 'Fairy Tail'),
    ('Ignition Gloves', 'Arma baseada em tecido revestidor da explosão faíscosa que instiga fogo das estrelas vermelhas que faísca pelo atrito dos socos em faísca nas linhas de frente extremas do ardor sem fim do herói incandescente vermelho de fogo em chamas de alquimia contínua de chamas.', 'Anime'),
    ('Instant Transmission', 'Desloca o corpo na imperceptível fraqueza da velocidade instantânea num desvio milimétrico ao encostar aos e localizar pelo ki o inimigo numa presença distante para queimar etapas dos céus e se projetar ou atacar ou fugir no nada intergalático de fuga imediato das viagens espaciais.', 'Dragon Ball'),
    ('Inverted Spear of Heaven', 'Uma lâmina peculiar com bordas invertidas e irregulares criadora de anulações absurdas, sua pura existência paralisa as curas naturais em carne ou técnicas alheias pela profundeza que atravessar em uma punhalada no peito para exterminar jujutsu da existência mágica da essência no além das sombras das maldições em sua extensão amaldiçoada pela brutal violência da guerra e armas divinas em seu gume bizarro infernal maciço contra maldições superiores da lança em um acerto de ferimentos incicatrizáveis eternos perfurantes inumeráveis contínuos no corpo em dor em sofrimento na carne.', 'Jujutsu Kaisen'),
    ('Jajanken', 'Pedra, Papel, Tesoura. Cada punho foca aura devastadora ou uma lâmina ou disparo em proporções colossais.', 'Hunter x Hunter'),
    ('Kaioken', 'Técnica que multiplica a força do usuário transbordando em aura vermelha, com forte tensão ao corpo.', 'Dragon Ball'),
    ('Kakuja Form', 'Forma incompleta brutal de canibalismo originando braços rústicos em formato simbiótico descontrolado e veloz.', 'Tokyo Ghoul'),
    ('Kamehameha', 'O lendário disparo de pura vida acumulada nas palmas iluminando tudo ao redor para varrer o mal num clarão cerúleo eterno.', 'Dragon Ball'),
    ('Kamish', 'Legado de um perigoso dragão, um poder dracônico em formato puro a fim de rasgar tudo o que toca a armadura ou o ar e a essência ao relento perigoso das fendas rasgadas escarlates.', 'Solo Leveling'),
    ('Kamish’s Wrath', 'A fúria de Kamish se encerra cortando com destreza indomável. As lâminas da ira dos monstros do abismo de fogo caótico rubro em chamas de magma.', 'Solo Leveling'),
    ('Kasaka’s Venom Fang', 'A presa da grande serpente. Um golpe que infunde paralisia e deterioração.', 'Solo Leveling'),
    ('Killua’s Yo-Yos', 'Feitos de liga pesada e carregados de tensão paralisadora. Movimento de surpresa tátio.', 'Hunter x Hunter'),
    ('Knight Killer', 'Lâmina serrilhada nascida do pesadelo sombrio feita para abater armaduras rígidas sob pontos vitais fraturados brutalmente.', 'Solo Leveling'),
    ('Kunai trovão', 'Kunai metálica infundida de eletricidade rápida focando rasgar couraças de defesa instantaneamente atirado ou empunhado com alta vibração de corte.', 'Naruto'),
    ('Kunai', 'Ferramenta básica de assassinos que sempre garante ataques flexíveis à curta e média distância com uma mira exímia e precisão afiada letal da furtividade nas sombras espionáveis dos espiões frios velozes e rápidos ninjas shinobis das sombras das árvores das florestas.', 'Naruto'),
    ('Kurapika’s Chains', 'As correntes que vinculam o coração e as almas a promessas perigosas letais de ardor no escárnio pelo rancor contra seu inimigo.', 'Hunter x Hunter'),
    ('Limitless', 'Uma defesa absoluta que fragmenta a distância. Você se aproxima lentamente de Zeno, sem nunca alcançar.', 'Jujutsu Kaisen'),
    ('Lostvayne', 'A demoníaca armadura curta focada para clones da imagem física exaurindo sua vida contra poder absurdo em chamas.', 'Seven Deadly Sins'),
    ('Mana Zone', 'Uma percepção vasta sobre cada resquício das magias do domínio estendidas ao relento permitindo atacar de cada lado inesperado omnidirecional dos cantos sem fim dos domínios em mana puros a volta em sincronia.', 'Black Clover'),
    ('Mascara hollow', 'Libera instintos devassos brancos ocultando o selo das trevas sob uma carranca que eleva ferocidade letal cega em dano na velocidade absurda dos gritos de fúria cega devorando tudo a volta impiedosos dos caçadores devoradores almas e hollows.', 'Bleach'),
    ('mera mera', 'Fogo em correntes chamejantes originadas das cinzas engolindo ou abraçando irmãos jurados do além das montanhas corajosas livres em fúrias abrasadoras dos oceanos sem destino no calor da aventura ou sol escaldante livre incandescente rubro quente fumegante dos laços em punhos de fogo que não cedem e queimam livres da determinação ardente escaldante de irmãos de revolução pirata das chamas das fogueiras quentes ou estrelas no amanhecer sol da fogueira inextinguível.', 'One Piece'),
    ('Meta Vision', 'Percepção absoluta para cobrir cada detalhe geométrico e antecipar sem pena a jogada exata.', 'Blue Lock'),
    ('Metal Vessel', 'Um recipiente místico evocador dos demônios e devaneios elementais originário de torres colossais das lendas desérticas inumanas.', 'Magi'),
    ('Millennium Puzzle', 'Relíquia complexa do faraó para distorcer apostas vitais sob um destino de jogos e duelos absolutos dos reinos assombrosos sem volta e jogos esmagadouros de trevas infernais sem salvação ou cura sem remédio na vida das tramas astutas milenares egípcias das ruínas esquecidas imortais sob os céus impiedosos sagrados com enigmas indecifráveis sem esperanças amaldiçoados caóticos dos sábios mestres escuros eternos cruéis punições em trevas sombrias insanas mentes assombrosas mortais perdições ou maldições de punições nos destinos dos reinos da antiguidade do tempo dos duelistas divinos faraós monstros magia astuta sem fundo sob poços escuros sem luz.', 'Yu-Gi-Oh!'),
    ('Mjolnir', 'A ferramenta final das trovoadas nórdicas. Apenas os colossais aguentam erguer isso esmagando a tudo em um raio e desespero imensurável caótico nos relâmpagos ruidosos celestes raios de Zeus trovões dos tempestuosos divinos esmagadores de crânios divinos titãs mortais raios do céu brutal na dor cega pesada dos martelos destruidores esmagadores que arrebentam ossos dos guerreiros eternos de Valhalla tempestades eternas da fúria celestial deuses dos céus raios da fúria pura em marteladas mortais brutais esmagadoras violentas sem piedade tempestuosas caóticas tempestades trovoadas da fúria do relâmpago eterno nórdico trovão escuro de faíscas raivosas fúria cega trovões trovoadas raios céus tormentas do infinito trovão sem fim nos raios dos céus celestes raios deuses da tormenta esmagando de fato no escuro das trevas o desespero e poeira relâmpago da morte fúria esmagadora nórdica nos gigantes trovoadora impiedosa na fúria violenta ruidosa divina celestial no além e no alto a luz da tempestade da dor celestial.', 'Record of Ragnarok'),
    ('Murasame', 'Um corte fátuo embebido num veneno incalculável que fulmina a vítima instantaneamente sem vacina em veias malditas impiedosas do fim em uma marca irreversível carcomendo do corte em segundos.', 'Akame ga Kill'),
    ('nichirin', 'As lâminas de cores diversas das faíscas lunares chamas ou neves desenhadas e forjadas pelo sol contra seres amaldiçoados de nevasca da noite cega eterna sombrios predadores noturnos comedores de almas na eterna imortal neblina em sangue.', 'Demon Slayer'),
    ('ODM Gear', 'Permanece em pleno ar nas amarras da sobrevivência nas garras de um caos devorador da opressão titânica do céu da liberdade e do terror voador dos guerreiros e garras dos titãs sem medo voador.', 'Attack on Titan'),
    ('One For All Smash', 'Energia imensa e violenta herdada pela determinação corajosa transmitida esmagando tudo pelo soco impiedoso absoluto num vento torrencial devastador de vácuos infinitos contra vilões de calamidades.', 'My Hero Academia'),
    ('Ora Barrage', 'Socos insondáveis e absurdamente incessantes de um espírito de pura punição raivosa e bruta na face ruidoso gritando pela brutal humilhação das escórias nas perdições da alma alheia batendo ossos.', 'JoJo'),
    ('Orb of Avarice', 'Globo sombrio sorvendo mana gananciosa das feridas abatidas pelas ganâncias absolutas de glória do jogador de nível extremo sombrio em glória das noites caçadoras na torre sombria.', 'Solo Leveling'),
    ('Papel explosivo', 'Truques sutis mas demolidores armadilhas rústicas das florestas que criam surpresas infernais num estardalhaço cruel explosivo violento na fumaça mortal no fogo letal sorrateiro dos espiões ocultos explosivos no escuro invisível ardilosamente de tocaia armadilha letal escondido nos cantos silenciosos astutos ninjas cruéis nas trevas da fumaça em explosões sem fim fogo das fagulhas destrutivas imensas silenciosas que matam em pedaços brutais repentinamente rústicas chamas faíscas.', 'Naruto'),
    ('Philosopher’s Stone', 'Pedra feita das almas inestimáveis, rompe amarras transcendentes permitindo conjurar tudo desrespeitando o preceito sem fronteiras cruéis de sangue derramado e caos imortal imenso.', 'Fullmetal Alchemist'),
    ('Playful Cloud', 'Arsenal contundente puro para os fortes porradeiros, que absorve fúria na ponta de barras impiedosas para amassar a magia dos deuses sombrios violentos com impacto nua e cru da forca braçal insana cru em puro pavor amaldiçoado cega em brutalidade massiva contra feitiçaria e crânios dos alvos divinos amaldiçoados fortes pesados.', 'Jujutsu Kaisen'),
    ('Potara Earrings', 'Elos que se não soltam. Engastam a combinação simultânea das habilidades unidas somando forças ou defeitos de duas lendas sem limite num poder formidável de pura fusão cósmica invencível de estrelas galáticas.', 'Dragon Ball'),
    ('Power Pole', 'O bastão celestial simples. Ignora distância pelas raízes divinas, castigando quem o subestima pelas distâncias esticadas sem limite estendido do topo aos confins inatingíveis para além de limites mortais impiedosos nos céus infinitos puros.', 'Dragon Ball'),
    ('Predator Eye', 'Instinto de artilheiro que espera o goleiro piscar. Lê o menor intervalo de defesa e transforma um ângulo impossível em finalização precisa.', 'Blue Lock'),
    ('Prison Realm', 'Um cubo selado por olhos inquietos, feito para prender até técnicas supremas quando a mente do alvo hesita diante da própria memória.', 'Jujutsu Kaisen'),
    ('Puppet naruto', 'Marionete shinobi de juntas ocultas, fios de chakra e lâminas escondidas, perfeita para atacar enquanto o verdadeiro mestre permanece fora do alcance.', 'Naruto'),
    ('Quick Attack', 'Ataque relâmpago de vôlei em sincronia total: levantamento cego, salto explosivo e uma cortada que atravessa o bloqueio antes da reação.', 'Haikyuu!!'),
    ('Quinque', 'Arma moldada de um kakuhou, fria e cirúrgica, usada por investigadores para enfrentar ghouls com a própria biologia monstruosa deles.', 'Tokyo Ghoul'),
    ('Requiem Arrow', 'Flecha capaz de levar um Stand além da própria forma, despertando uma vontade soberana que reescreve o resultado do confronto.', 'JoJo'),
    ('Requiem', 'Evolução absoluta de um Stand, onde intenção, destino e ataque se curvam a uma presença que devolve qualquer ameaça ao zero.', 'JoJo'),
    ('Return by Death', 'Maldição de retorno que guarda memórias entre mortes. Cada queda reinicia o tabuleiro, mas deixa cicatrizes invisíveis no usuário.', 'Re:Zero'),
    ('Rhitta', 'Machado sagrado que acumula calor solar até o meio-dia, tornando cada golpe pesado como a arrogância flamejante de Escanor.', 'Seven Deadly Sins'),
    ('Rinkaku Kagune', 'Tentáculos de kagune brotam como membros famintos, combinando regeneração agressiva e golpes flexíveis que perfuram a defesa inimiga.', 'Tokyo Ghoul'),
    ('Ruler’s Authority', 'Telecinese de monarca que agarra o espaço sem tocar. Puxa, arremessa e esmaga alvos como se a gravidade obedecesse a uma ordem direta.', 'Solo Leveling'),
    ('samehada', 'Espada viva coberta de escamas, devora chakra a cada contato e prefere mestres com reservas monstruosas de energia.', 'Naruto'),
    ('Scouter', 'Visor de combate saiyajin que mede poder de luta, rastreia presença e transforma arrogância em cálculo antes do primeiro disparo de ki.', 'Dragon Ball'),
    ('Sekki', 'Shinki afiado de Noragami, nascido de uma alma sem descanso e transformado em lâmina capaz de cortar criaturas da margem distante.', 'Noragami'),
    ('Senbonzakura', 'Zanpakutō que se desfaz em milhares de pétalas cortantes. A beleza da técnica esconde uma tempestade de lâminas microscópicas.', 'Bleach'),
    ('Senzu Bean', 'Feijão sagrado de recuperação total, capaz de fechar feridas, restaurar energia e devolver um guerreiro exausto ao combate.', 'Dragon Ball'),
    ('Shadow Extraction', 'Comando necromântico que arranca a sombra de inimigos derrotados, convocando servos leais para marchar sob o exército do monarca.', 'Solo Leveling'),
    ('Sharingan', 'Dōjutsu escarlate que lê movimentos, copia técnicas e prende o inimigo em ilusões onde cada segundo pode decidir a luta.', 'Naruto'),
    ('Skull Knight Sword', 'Lâmina impossível do Cavaleiro Caveira, forjada para abrir caminho entre apóstolos, causalidade e horrores do mundo astral.', 'Berserk'),
    ('Soul Resonance', 'Sincronia entre meister e arma demoníaca, amplificando frequência de alma até o golpe vibrar direto contra a essência do alvo.', 'Soul Eater'),
    ('Spirit Gun', 'Disparo espiritual concentrado na ponta do dedo, simples no gesto e devastador quando a energia de Yusuke explode em linha reta.', 'Yu Yu Hakusho'),
    ('Split Soul Katana', 'Katana que ignora a dureza do corpo e corta o contorno da alma, punindo defesas físicas com precisão amaldiçoada.', 'Jujutsu Kaisen'),
    ('Staff of Frieren', 'Cajado de maga élfica talhado para feitiços metódicos. Sua força está na calma de quem estudou magia por eras.', 'Frieren'),
    ('Stand Arrow', 'Flecha ligada ao vírus dos Stands, capaz de despertar uma manifestação espiritual em quem suporta seu julgamento.', 'JoJo'),
    ('State Alchemist Watch', 'Relógio de prata dos alquimistas estatais, símbolo de autoridade militar e foco para transmutar conhecimento em ação imediata.', 'Fullmetal Alchemist'),
    ('Stealth', 'Habilidade de assassino caçador que apaga presença e intenção, deixando apenas o instante em que a lâmina já encontrou o ponto fraco.', 'Solo Leveling'),
    ('Steel Balls', 'Esferas de rotação perfeita, usadas para transferir Spin pelo ar, pelos músculos e pela trajetória improvável do destino.', 'JoJo'),
    ('Stone Mask', 'Máscara asteca que perfura o cérebro ao tocar sangue, libertando uma evolução vampírica cruel e uma fome sem humanidade.', 'JoJo'),
    ('Survey Corps cloak', 'Manto das Asas da Liberdade, marcado por expedições além das muralhas e pela coragem de avançar mesmo diante de titãs.', 'Attack on Titan'),
    ('Ten Shadows', 'Técnica herdada que invoca shikigami a partir das sombras, alternando perseguição, defesa e domínio do campo de batalha.', 'Jujutsu Kaisen'),
    ('tensa zanguetsu', 'Bankai compacto de Ichigo, condensando pressão espiritual e velocidade em uma lâmina negra feita para duelos decisivos.', 'Bleach'),
    ('Thunder Spears', 'Lanças explosivas criadas para perfurar couraças titânicas, disparadas em alta velocidade antes de detonar no ponto vulnerável.', 'Attack on Titan'),
    ('Thunderclap and Flash', 'Respiração do Trovão em um único passo. O corpo some no clarão e a lâmina chega junto do estrondo.', 'Demon Slayer'),
    ('Time Stop', 'Domínio de segundos roubados do mundo. Enquanto tudo congela, apenas o usuário e seu Stand decidem onde o golpe final cairá.', 'JoJo'),
    ('Titan serum', 'Soro de transformação eldiana, capaz de converter desespero humano em força titânica e herança monstruosa.', 'Attack on Titan'),
    ('Titan Shift', 'Poder de transformar o próprio corpo em titã, unindo vontade humana, regeneração brutal e presença de campo esmagadora.', 'Attack on Titan'),
    ('Ultra Instinct', 'Estado em que o corpo reage antes do pensamento, esquivando e atacando com serenidade divina sem desperdiçar movimento.', 'Dragon Ball'),
    ('Ultrahard Steel Blades', 'Lâminas descartáveis de aço ultraduro, desenhadas para cortar a nuca de titãs em manobras rápidas do equipamento tridimensional.', 'Attack on Titan'),
    ('Unlimited Blade Works', 'Mundo interno de lâminas infinitas, onde cada arma copiada repousa pronta para chover aço sobre qualquer inimigo.', 'Fate'),
    ('Volundr', 'Vínculo entre humano e valquíria que transforma alma em arma divina, permitindo enfrentar deuses em igualdade por um instante.', 'Fate'),
    ('Water Breathing', 'Respiração fluida que guia cortes como correnteza, alternando defesa, avanço e precisão contra demônios.', 'Demon Slayer'),
    ('Z Sword', 'Espada lendária do Mundo Sagrado, pesada o bastante para treinar deuses e testar a força de quem ousa empunhá-la.', 'Dragon Ball'),
    ('Zoltraak', 'Feitiço ofensivo que já foi ameaça demoníaca absoluta e virou fundamento moderno, refinado para atravessar defesas mágicas.', 'Frieren')
)
UPDATE public.shop_items s
SET description = l.description,
    source_anime = l.source_anime
FROM new_lore l
WHERE s.name = l.name;
