-- Gerado por scripts/sql/wit2-virada.ts (não editar à mão). Vem depois de _wit2_virada.sql.
BEGIN;
INSERT INTO public.wit2_shop_map (shop_name, card_id) VALUES
  ('Manto da Aurora (Edição Premium)', 'manto-da-aurora'),
  ('Pacto Demoníaco', 'pacto-demoniaco'),
  ('Modo Sábio dos Seis Caminhos', 'modo-sabio-dos-seis-caminhos'),
  ('Aegis Celestial (Edição Premium)', 'aegis-celestial'),
  ('Arthur’s Excalibur', 'excalibur-de-arthur'),
  ('Berserker Rag', 'furia-berserker'),
  ('BOTAS DE COURO', 'botas-de-couro'),
  ('Cannon Arm', 'braco-canhao'),
  ('Dark Magician', 'mago-negro'),
  ('Disaster', 'disaster'),
  ('enma', 'enma'),
  ('Erasure', 'apagar'),
  ('Explosion Rush', 'explosion-rush'),
  ('foice tripla', 'foice-tripla'),
  ('gomu gomu no mi', 'gomu-gomu-no-mi'),
  ('gura gura', 'gura-gura-no-mi'),
  ('Half-Cold Half-Hot', 'metade-gelo-metade-fogo'),
  ('Hamon Overdrive', 'hamon-overdrive'),
  ('Instant Transmission', 'teletransporte'),
  ('Knight Killer', 'matadora-de-cavaleiros'),
  ('Kurapika’s Chains', 'correntes-de-kurapika'),
  ('Mana Zone', 'zona-de-mana'),
  ('mera mera', 'mera-mera-no-mi'),
  ('nichirin', 'lamina-nichirin'),
  ('Ora Barrage', 'ora-ora-ora'),
  ('PEITORAL DE COURO', 'peitoral-de-couro'),
  ('Predator Eye', 'olho-de-predador'),
  ('Puppet naruto', 'marionete-venenosa'),
  ('Quick Attack', 'ataque-rapido'),
  ('Quinque', 'quinque'),
  ('Rinkaku Kagune', 'kagune-rinkaku'),
  ('samehada', 'samehada'),
  ('Sekki', 'sekki'),
  ('Sharingan', 'sharingan'),
  ('Staff of Frieren', 'cajado-de-frieren'),
  ('Baruka’s Dagger', 'adaga-de-baruka'),
  ('Black Divider', 'black-divider'),
  ('Chain Jail', 'prisao-de-correntes'),
  ('Cursed Speech', 'fala-amaldicoada'),
  ('Fire Dragon Roar', 'rugido-do-dragao-de-fogo'),
  ('Golpe Conquistador', 'golpe-conquistador'),
  ('Hinokami Kagura', 'hinokami-kagura'),
  ('Inverted Spear of Heaven', 'lanca-invertida-do-ceu'),
  ('Kakuja Form', 'forma-kakuja'),
  ('Kasaka’s Venom Fang', 'presa-venenosa-de-kasaka'),
  ('One For All Smash', 'smash-do-one-for-all'),
  ('Orb of Avarice', 'orbe-da-avareza'),
  ('Playful Cloud', 'nuvem-brincalhona'),
  ('Prison Realm', 'reino-da-prisao'),
  ('Punho de Ferro', 'punho-de-ferro'),
  ('Split Soul Katana', 'katana-parte-alma'),
  ('Ten Shadows', 'dez-sombras'),
  ('Toque de Decadência', 'toque-de-decadencia'),
  ('Black Whip', 'chicote-negro'),
  ('Bungee Gum', 'chiclete-elastico'),
  ('Chastiefol', 'chastiefol'),
  ('Death Scythe', 'foice-da-morte'),
  ('Demon Sword Ragnarok', 'espada-demoniaca-ragnarok'),
  ('Dragon Slayer', 'matadora-de-dragoes'),
  ('Espírito da Besta', 'espirito-da-besta'),
  ('Gáe Bolg', 'gae-bolg'),
  ('Gideon', 'gideon'),
  ('Hyorinmaru', 'hyorinmaru'),
  ('Lostvayne', 'lostvayne'),
  ('Mjolnir', 'mjolnir'),
  ('Murasame', 'murasame'),
  ('Rhitta', 'rhitta'),
  ('Senbonzakura', 'senbonzakura'),
  ('tensa zanguetsu', 'tensa-zangetsu'),
  ('Volundr', 'volundr'),
  ('Z Sword', 'espada-z'),
  ('Avalon', 'avalon'),
  ('Dragon of the Darkness Flame', 'dragao-das-chamas-negras'),
  ('Excalibur', 'excalibur'),
  ('Hollow Purple', 'vazio-roxo'),
  ('Kagune Liberado', 'kagune-liberado'),
  ('Kyoka Suigetsu', 'kyoka-suigetsu'),
  ('Limitless', 'ilimitado'),
  ('Spirit Gun', 'reigan'),
  ('Unlimited Blade Works', 'unlimited-blade-works'),
  ('Adolla Burst', 'adolla-burst'),
  ('Automail Blade', 'lamina-de-automail'),
  ('Benimaru’s Crimson Moon', 'lua-carmesim-de-benimaru'),
  ('Dark Shadow', 'dark-shadow'),
  ('Dragon Cleave', 'corte-do-dragao'),
  ('Lâmina Estelar (Edição Premium)', 'lamina-estelar'),
  ('Skull Knight Sword', 'espada-do-cavaleiro-da-caveira'),
  ('Gon’s Fishing Rod', 'vara-de-pesca-do-gon'),
  ('Hisoka’s Cards', 'cartas-do-hisoka'),
  ('Ignition Gloves', 'luvas-de-ignicao'),
  ('Killua’s Yo-Yos', 'ioios-do-killua'),
  ('Kunai', 'kunai'),
  ('Kunai trovão', 'kunai-do-deus-do-trovao'),
  ('Papel explosivo', 'papel-explosivo'),
  ('Power Pole', 'bastao-magico'),
  ('Thunder Spears', 'lancas-trovao'),
  ('Ultrahard Steel Blades', 'laminas-de-aco-ultraduro'),
  ('Coordenadas do Titã Fundador', 'coordenada'),
  ('Enuma Elish', 'enuma-elish'),
  ('Kamish', 'kamish-o-dragao'),
  ('Kamish’s Wrath', 'furia-de-kamish'),
  ('Requiem', 'king-crimson'),
  ('Return by Death', 'retorno-pela-morte'),
  ('Time Leap', 'time-leap'),
  ('Behelit', 'behelit'),
  ('ESPADA SIMPLES', 'espada-simples'),
  ('Espadinha', 'espadinha'),
  ('Fairy Tail Mark', 'marca-da-fairy-tail'),
  ('Metal Vessel', 'recipiente-de-metal'),
  ('Millennium Puzzle', 'enigma-do-milenio'),
  ('Pequena espada', 'pequena-espada'),
  ('Steel Balls', 'esferas-de-aco'),
  ('Survey Corps cloak', 'capa-da-tropa-de-exploracao'),
  ('Titan serum', 'soro-de-tita'),
  ('Berserker Armor', 'armadura-berserker'),
  ('Coroa do Crepúsculo (Premium)', 'coroa-do-crepusculo'),
  ('Philosopher’s Stone', 'pedra-filosofal'),
  ('Potara Earrings', 'brincos-potara'),
  ('Stand Arrow', 'flecha-do-stand'),
  ('Stone Mask', 'mascara-de-pedra'),
  ('Dragon Balls', 'esferas-do-dragao'),
  ('Requiem Arrow', 'flecha-requiem'),
  ('Dragon Lacrima', 'lacrima-de-dragao'),
  ('Erza’s Armors', 'armaduras-da-erza'),
  ('Mascara hollow', 'mascara-hollow'),
  ('ODM Gear', 'equipamento-3d'),
  ('Scouter', 'scouter'),
  ('Senzu Bean', 'semente-dos-deuses'),
  ('State Alchemist Watch', 'relogio-de-alquimista-federal'),
  ('Bloodlust', 'sede-de-sangue'),
  ('Direct Shot', 'chute-direto'),
  ('Ice Make', 'ice-make'),
  ('Jajanken', 'jajanken'),
  ('Meta Vision', 'meta-visao'),
  ('Ruler’s Authority', 'autoridade-do-governante'),
  ('Soul Resonance', 'ressonancia-de-almas'),
  ('Stealth', 'furtividade'),
  ('Titan Shift', 'transformacao-em-tita'),
  ('Water Breathing', 'respiracao-da-agua'),
  ('Anti-Magic Slash', 'corte-antimagia'),
  ('Black Flash', 'black-flash'),
  ('Caixão das Estrelas', 'caixao-das-estrelas'),
  ('Cruel Sun', 'sol-cruel'),
  ('Dimension Slash', 'corte-dimensional'),
  ('Dragon Force', 'dragon-force'),
  ('Equivalent Exchange', 'troca-equivalente'),
  ('Final Flash', 'final-flash'),
  ('Flame Alchemy', 'alquimia-das-chamas'),
  ('Fogo Infernal', 'fogo-infernal'),
  ('Full Counter', 'full-counter'),
  ('Godspeed', 'velocidade-divina'),
  ('Kaioken', 'kaioken'),
  ('Kamehameha', 'kamehameha'),
  ('Magia de Roswaal', 'magia-de-roswaal'),
  ('Ope Ope no Mi (ROOM)', 'room'),
  ('Orbe Cromático (Edição Premium)', 'orbe-cromatico'),
  ('Rugido do Titã Fundador', 'rugido-do-tita-fundador'),
  ('Shadow Extraction', 'extracao-de-sombras'),
  ('Soul Switch', 'troca-de-almas'),
  ('Thunderclap and Flash', 'primeira-forma-relampago'),
  ('Big Bang Attack', 'big-bang-attack'),
  ('Edo Tensei', 'edo-tensei'),
  ('Jaula de Espinhos', 'jaula-de-espinhos'),
  ('O Avatar', 'estado-avatar'),
  ('Contrato com o Diabo', 'contrato-com-o-diabo'),
  ('Domain Expansion', 'expansao-de-dominio'),
  ('Haki do Rei Conquistador', 'haki-do-rei'),
  ('Zoltraak', 'zoltraak'),
  ('Campo de Hidratação', 'campo-de-hidratacao'),
  ('Geass Eye', 'olho-do-geass'),
  ('Modo 100%', 'modo-100'),
  ('Time Stop', 'za-warudo'),
  ('Ultra Instinct', 'instinto-superior'),
  ('Selo do Vazio (Premium)', 'selo-do-vazio')
ON CONFLICT (shop_name) DO UPDATE SET card_id = EXCLUDED.card_id;
INSERT INTO public.wit2_class_path (ord, word, path_id) VALUES
  (0, 'guerreiro', 'desafiante'),
  (0, 'warrior', 'desafiante'),
  (1, 'mago', 'sabio'),
  (1, 'mage', 'sabio'),
  (2, 'berserker', 'louco'),
  (2, 'barbaro', 'louco'),
  (3, 'paladino', 'guardiao'),
  (3, 'clerigo', 'guardiao'),
  (3, 'tanque', 'guardiao'),
  (4, 'alquimista', 'alquimista'),
  (4, 'druida', 'alquimista'),
  (5, 'necromante', 'ceifador'),
  (6, 'espiao', 'trapaceiro'),
  (6, 'ladino', 'trapaceiro'),
  (6, 'assassino', 'trapaceiro'),
  (7, 'ferreiro', 'forjador'),
  (7, 'arqueiro', 'forjador'),
  (7, 'cavaleiro', 'forjador')
ON CONFLICT (word) DO UPDATE SET ord = EXCLUDED.ord, path_id = EXCLUDED.path_id;
COMMIT;
